[package]
name = "syster"
version = "0.1.0"
authors = ["John Baublitz <john.m.baublitz@gmail.com>"]
description = ""
license = "BSD-3-Clause"
repository = "https://github.com/jbaublitz/syster"
keywords = ["syscall", "linux"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "LICENSE",
]
