(function() {var implementors = {};
implementors["syster"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"syster/type.SyscallRet.html\" title=\"type syster::SyscallRet\">SyscallRet</a>&gt; for <a class=\"enum\" href=\"syster/enum.Zero.html\" title=\"enum syster::Zero\">Zero</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"syster/type.SyscallRet.html\" title=\"type syster::SyscallRet\">SyscallRet</a>&gt; for <a class=\"struct\" href=\"syster/struct.Error.html\" title=\"struct syster::Error\">Error</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"syster/type.SyscallRet.html\" title=\"type syster::SyscallRet\">SyscallRet</a>&gt; for <a class=\"struct\" href=\"syster/struct.Pid.html\" title=\"struct syster::Pid\">Pid</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"syster/type.SyscallRet.html\" title=\"type syster::SyscallRet\">SyscallRet</a>&gt; for <a class=\"struct\" href=\"syster/struct.Id.html\" title=\"struct syster::Id\">Id</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"syster/type.SyscallRet.html\" title=\"type syster::SyscallRet\">SyscallRet</a>&gt; for <a class=\"struct\" href=\"syster/struct.Fd.html\" title=\"struct syster::Fd\">Fd</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"syster/type.SyscallRet.html\" title=\"type syster::SyscallRet\">SyscallRet</a>&gt; for <a class=\"struct\" href=\"syster/struct.Int.html\" title=\"struct syster::Int\">Int</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"type\" href=\"syster/type.SyscallRet.html\" title=\"type syster::SyscallRet\">SyscallRet</a>&gt; for <a class=\"struct\" href=\"syster/struct.Never.html\" title=\"struct syster::Never\">Never</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
